#### Carga de datos extraidos de Twitter y análisis de sus atributos.

Se van a cargar tweets desde un fichero .json que se ha generado a partir de un script python, que conecta con la API de Twitter streaming y recoge tweets, usando las credenciales necesarias.

In [1]:
# imports necesarios
import pandas as pd
import json

In [2]:
# cargamos los tweets desde el fichero json
df = pd.read_json('./data/stream_test.json', orient='columns', lines=True)

# vemos los primeros registros
df.head(10)

,contributors,coordinates,created_at,display_text_range,entities,extended_entities,extended_tweet,favorite_count,favorited,filter_level,...,reply_count,retweet_count,retweeted,retweeted_status,source,text,timestamp_ms,truncated,user,withheld_in_countries
0,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,NaN,0.0,0.0,low,...,0.0,0.0,0.0,{'created_at': 'Sun Nov 11 08:11:20 +0000 2018...,"<a href=""http://twitter.com/download/iphone"" r...",RT @sanadrianfever: La crónica de hoy en @ElPe...,2018-11-11 16:34:07.228,0.0,"{'id': 792419113, 'id_str': '792419113', 'name...",NaN
1,NaN,None,2018-11-11 16:34:07,"[8, 15]","{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low,...,0.0,0.0,0.0,NaN,"<a href=""http://twitter.com/download/android"" ...",@EJFC26 Y Messi,2018-11-11 16:34:07.254,0.0,"{'id': 207220995, 'id_str': '207220995', 'name...",NaN
2,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low,...,0.0,0.0,0.0,{'created_at': 'Sun Nov 11 16:27:54 +0000 2018...,"<a href=""http://twitter.com/download/iphone"" r...",RT @Troyanoyoya: Con el partido que esta hacie...,2018-11-11 16:34:07.548,0.0,"{'id': 289264713, 'id_str': '289264713', 'name...",NaN
3,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low,...,0.0,0.0,0.0,{'created_at': 'Sun Nov 11 10:25:52 +0000 2018...,"<a href=""http://twitter.com/download/android"" ...",RT @MqGuardiaCivil: Así reciben a nuestra @gua...,2018-11-11 16:34:07.657,0.0,"{'id': 1011639837995266049, 'id_str': '1011639...",NaN
4,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low,...,0.0,0.0,0.0,NaN,"<a href=""http://twitter.com/download/android"" ...",Rakitic mierdaaaaa,2018-11-11 16:34:07.673,0.0,"{'id': 185025378, 'id_str': '185025378', 'name...",NaN
5,NaN,None,2018-11-11 16:34:07,"[0, 82]","{'hashtags': [], 'urls': [{'url': 'https://t.c...","{'media': [{'id': 1061658334695051264, 'id_str...",NaN,0.0,0.0,low,...,0.0,0.0,0.0,NaN,"<a href=""https://dlvrit.com/"" rel=""nofollow"">d...",Messi vuelve en el mejor momento de Suárez htt...,2018-11-11 16:34:07.604,0.0,"{'id': 72750552, 'id_str': '72750552', 'name':...",NaN
6,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low,...,0.0,0.0,0.0,{'created_at': 'Sun Nov 11 14:36:27 +0000 2018...,"<a href=""http://twitter.com/download/iphone"" r...",RT @FranciaMessi: Messi en Liga :\n427 matchs\...,2018-11-11 16:34:07.835,0.0,"{'id': 1000659764903383040, 'id_str': '1000659...",NaN
7,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low,...,0.0,0.0,0.0,{'created_at': 'Sun Nov 11 15:50:42 +0000 2018...,"<a href=""http://twitter.com/download/android"" ...",RT @polibueno691: @RubenSanchezTW En la anteri...,2018-11-11 16:34:07.832,0.0,"{'id': 1054990994326908928, 'id_str': '1054990...",NaN
8,NaN,None,2018-11-11 16:34:08,NaN,"{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,NaN,0.0,0.0,low,...,0.0,0.0,0.0,NaN,"<a href=""http://www.les-livres.fr"" rel=""nofoll...",FC Barcelona vs Betis en directo | Laliga 2018...,2018-11-11 16:34:08.099,0.0,"{'id': 468507589, 'id_str': '468507589', 'name...",NaN
9,NaN,None,2018-11-11 16:34:08,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low,...,0.0,0.0,0.0,NaN,"<a href=""http://twitter.com/download/android"" ...",@F_deFIFA quien tenía a Messi en este partido ...,2018-11-11 16:34:08.088,0.0,"{'id': 2980865522, 'id_str': '2980865522', 'na...",NaN

In [3]:
# vemos el tamaño del DF y las columnas/atributos de los datos
print("num_rows: %d\tColumnas: %d\n" % (df.shape[0], df.shape[1]) )
print("Columnas:\n", list(df.columns))

num_rows: 7633	Columnas: 38

Columnas:
 ['contributors', 'coordinates', 'created_at', 'display_text_range', 'entities', 'extended_entities', 'extended_tweet', 'favorite_count', 'favorited', 'filter_level', 'geo', 'id', 'id_str', 'in_reply_to_screen_name', 'in_reply_to_status_id', 'in_reply_to_status_id_str', 'in_reply_to_user_id', 'in_reply_to_user_id_str', 'is_quote_status', 'lang', 'limit', 'place', 'possibly_sensitive', 'quote_count', 'quoted_status', 'quoted_status_id', 'quoted_status_id_str', 'quoted_status_permalink', 'reply_count', 'retweet_count', 'retweeted', 'retweeted_status', 'source', 'text', 'timestamp_ms', 'truncated', 'user', 'withheld_in_countries']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7633 entries, 0 to 7632
Data columns (total 38 columns):
contributors                 0 non-null float64
coordinates                  7 non-null object
created_at                   7622 non-null datetime64[ns]
display_text_range           611 non-null object
entities                     7622 non-null object
extended_entities            1048 non-null object
extended_tweet               453 non-null object
favorite_count               7622 non-null float64
favorited                    7622 non-null float64
filter_level                 7622 non-null object
geo                          7 non-null object
id                           7622 non-null float64
id_str                       7622 non-null float64
in_reply_to_screen_name      471 non-null object
in_reply_to_status_id        441 non-null float64
in_reply_to_status_id_str    441 non-null float64
in_reply_to_user_id          471 non-null float64
in_reply_to_user_id_str      471 non-null float64
is_quote_status              7622 non-null float64
lang                         7622 non-null object
limit                        11 non-null object
place                        182 non-null object
possibly_sensitive           1546 non-null float64
quote_count                  7622 non-null float64
quoted_status                491 non-null object
quoted_status_id             491 non-null float64
quoted_status_id_str         491 non-null float64
quoted_status_permalink      491 non-null object
reply_count                  7622 non-null float64
retweet_count                7622 non-null float64
retweeted                    7622 non-null float64
retweeted_status             3440 non-null object
source                       7622 non-null object
text                         7622 non-null object
timestamp_ms                 7622 non-null datetime64[ns]
truncated                    7622 non-null float64
user                         7622 non-null object
withheld_in_countries        7 non-null object
dtypes: datetime64[ns](2), float64(18), object(18)
memory usage: 2.2+ MB

In [5]:
# vemos el texto de los 10 primeros tweets
df['text'].head(10)

0    RT @sanadrianfever: La crónica de hoy en @ElPe...
1                                      @EJFC26 Y Messi
2    RT @Troyanoyoya: Con el partido que esta hacie...
3    RT @MqGuardiaCivil: Así reciben a nuestra @gua...
4                                   Rakitic mierdaaaaa
5    Messi vuelve en el mejor momento de Suárez htt...
6    RT @FranciaMessi: Messi en Liga :\n427 matchs\...
7    RT @polibueno691: @RubenSanchezTW En la anteri...
8    FC Barcelona vs Betis en directo | Laliga 2018...
9    @F_deFIFA quien tenía a Messi en este partido ...
Name: text, dtype: object

In [6]:
# partir el DF en varios para visualizar de forma más sencilla sus columnas
df_uno = df.iloc[:,:10]
df_dos = df.iloc[:,10:20]
df_tres = df.iloc[:,20:30]
df_cuatro = df.iloc[:,30:]

In [7]:
df_uno.head()

,contributors,coordinates,created_at,display_text_range,entities,extended_entities,extended_tweet,favorite_count,favorited,filter_level
0,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,NaN,0.0,0.0,low
1,NaN,None,2018-11-11 16:34:07,"[8, 15]","{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low
2,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low
3,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low
4,NaN,None,2018-11-11 16:34:07,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,0.0,low

In [8]:
df_dos.head()

,geo,id,id_str,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,is_quote_status,lang
0,None,1.061658e+18,1.061658e+18,None,NaN,NaN,NaN,NaN,0.0,es
1,None,1.061658e+18,1.061658e+18,EJFC26,1.061658e+18,1.061658e+18,1.931169e+09,1.931169e+09,0.0,fr
2,None,1.061658e+18,1.061658e+18,None,NaN,NaN,NaN,NaN,0.0,es
3,None,1.061658e+18,1.061658e+18,None,NaN,NaN,NaN,NaN,1.0,es
4,None,1.061658e+18,1.061658e+18,None,NaN,NaN,NaN,NaN,0.0,es

In [9]:
df_tres.head()

,limit,place,possibly_sensitive,quote_count,quoted_status,quoted_status_id,quoted_status_id_str,quoted_status_permalink,reply_count,retweet_count
0,NaN,None,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0
1,NaN,None,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0
2,NaN,None,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0
3,NaN,None,NaN,0.0,{'created_at': 'Sat Nov 10 13:18:46 +0000 2018...,1.061247e+18,1.061247e+18,"{'url': 'https://t.co/v604gGwNpO', 'expanded':...",0.0,0.0
4,NaN,None,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0

In [10]:
df_cuatro.head()

,retweeted,retweeted_status,source,text,timestamp_ms,truncated,user,withheld_in_countries
0,0.0,{'created_at': 'Sun Nov 11 08:11:20 +0000 2018...,"<a href=""http://twitter.com/download/iphone"" r...",RT @sanadrianfever: La crónica de hoy en @ElPe...,2018-11-11 16:34:07.228,0.0,"{'id': 792419113, 'id_str': '792419113', 'name...",NaN
1,0.0,NaN,"<a href=""http://twitter.com/download/android"" ...",@EJFC26 Y Messi,2018-11-11 16:34:07.254,0.0,"{'id': 207220995, 'id_str': '207220995', 'name...",NaN
2,0.0,{'created_at': 'Sun Nov 11 16:27:54 +0000 2018...,"<a href=""http://twitter.com/download/iphone"" r...",RT @Troyanoyoya: Con el partido que esta hacie...,2018-11-11 16:34:07.548,0.0,"{'id': 289264713, 'id_str': '289264713', 'name...",NaN
3,0.0,{'created_at': 'Sun Nov 11 10:25:52 +0000 2018...,"<a href=""http://twitter.com/download/android"" ...",RT @MqGuardiaCivil: Así reciben a nuestra @gua...,2018-11-11 16:34:07.657,0.0,"{'id': 1011639837995266049, 'id_str': '1011639...",NaN
4,0.0,NaN,"<a href=""http://twitter.com/download/android"" ...",Rakitic mierdaaaaa,2018-11-11 16:34:07.673,0.0,"{'id': 185025378, 'id_str': '185025378', 'name...",NaN

#### Repasando las diferentes columnas y la información que cada una contiene, nos quedaríamos con las siguientes columnas como las que contienen información verdaderamente relevante para posteriores análisis con los datos:

● extended_entities: Cuando el tweet contiene entre una y cuatro fotos nativas, o un video, o un GIF animado, contiene un array de metadatos 'multimedia'. 

● extended_tweet: texto del tweet extendido.

● in_reply_to_screen_name: Anulable. Si el Tweet representado es una respuesta, este campo contendrá el nombre de pantalla del autor del Tweet original.

● possibly_sensitive: Anulable. Este campo solo aparece cuando un Tweet contiene un enlace. El significado del campo no se refiere al contenido del Tweet en sí, sino que es un indicador de que la URL contenida en el Tweet puede contener contenido o medios identificados como contenido sensible.

● source: Utilidad usada para publicar el Tweet como una cadena con formato HTML. Los tweets del sitio web de Twitter tienen un valor fuente de web. Ejemplo: "fuente": "Twitter para Mac".

● timestamp_ms 

● truncated: Indica si el valor del parámetro de texto se truncó, por ejemplo, como resultado de un retweet que excede el límite de longitud del texto original de Tweet de 140 caracteres. El texto truncado terminará en puntos suspensivos, como este ... 

● created_at: Es la fecha en la cual se ha escrito el tweet. Se encuentra en formato UTC, la cual contiene la siguiente información ordenada y separada por espacios:

    ○ Día de la semana abreviado en inglés.

    ○ Mes del año abreviado en inglés.

    ○ Día del mes en formato numérico.

    ○ Hora, minutos y segundos en formato numérico separados por dos puntos.

    ○ Zona horaria en formato numérico.

    ○ Año en formato numérico.

● coordinates: Localización geográfica, especificada por el usuario u otra aplicación. Aparece en formato
geoJSON (longitud, latitud).

● entities: Es un objeto que contiene información sobre las distintas “entidades” que puede contener un tweet, que son las siguientes:

    ○ hashtags: Lista de objetos que contiene información sobre los hashtags que contiene el tweet.

    ○ urls: Lista de objetos que contiene información sobre las urls que contiene el tweet.

    ○ user_mentions: Lista de objetos que contiene información sobre los usuarios que menciona el tweet. Para que considere que mencionas a otro usuario, se tiene que poner un “@” delante del nombre de la personas que quieras mencionar.

    ○ symbols: Lista de objetos que contiene información sobre los “símbolos” que contiene el tweet. Para que se considere un “símbolo“, debe cumplir con la siguiente expresión regular: \ $[a-z]{1,6}([._][a-z]{1,2})? [12].

● favorite_count: Número de “me gusta” que ha recibido el tweet.

● id e id_str: Es la id única por tweet que lo representa, en formato numérico y string respectivamente.

● lang: Idioma en el cual está escrito el tweet.

● quote_count: Número de citas que ha recibido el tweet.

● quoted_status: contiene dentro el JSON del tweet al que citan.

● reply_count: Número de respuestas que ha recibido el tweet.

● retweet_count: Número de retweet que ha recibido el tweet.

● retweeted_status: contiene dentro el JSON del tweet al cual se le ha hecho retweet.

● text: Aquí se encuentra el texto del tweet siempre y cuando no sea superior a 140 caracteres. En el caso de que sea superior, solo habrá una parte y para ver el texto completo habría que consultar el atributo “full_text” dentro del atributo “extended_tweet”.

● user: Es un objeto con varios atributos sobre el usuario que haya escrito el tweet. Algunos de estos atributos son:

    ○ id e id_str: Es la id única por usuario que lo representa, en formato numérico y string respectivamente.

    ○ name: El nombre del usuario.

    ○ location: La localización del usuario si la ha puesto. En caso contrario, aparece null.

    ○ verified: Es un Booleano que indica si la cuenta del usuario está verificada o no.

    ○ followers_count: Número de seguidores que tiene ese usuario.

    ○ geo_enabled: Booleano que indica si el usuario tiene activada o no la geolocalización, para que cuando escriba un tweet, se almacene en este desde donde se ha escrito.

In [32]:
# crear otro dataframe a partir del primero con los atributos que queramos
df_final = pd.DataFrame()
lista = ['id', 'id_str', 'text', 'truncated', 'extended_tweet', 'entities', 'extended_entities', 'retweet_count',\
    'retweeted_status', 'reply_count', 'quote_count', 'quoted_status', 'favorite_count', 'in_reply_to_screen_name',\
    'possibly_sensitive', 'source', 'coordinates', 'lang', 'timestamp_ms', 'created_at', 'user']
df_final = df[lista]
df_final.head()

,id,id_str,text,truncated,extended_tweet,entities,extended_entities,retweet_count,retweeted_status,reply_count,...,quoted_status,favorite_count,in_reply_to_screen_name,possibly_sensitive,source,coordinates,lang,timestamp_ms,created_at,user
0,1.061658e+18,1.061658e+18,RT @sanadrianfever: La crónica de hoy en @ElPe...,0.0,NaN,"{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,0.0,{'created_at': 'Sun Nov 11 08:11:20 +0000 2018...,0.0,...,NaN,0.0,None,0.0,"<a href=""http://twitter.com/download/iphone"" r...",None,es,2018-11-11 16:34:07.228,2018-11-11 16:34:07,"{'id': 792419113, 'id_str': '792419113', 'name..."
1,1.061658e+18,1.061658e+18,@EJFC26 Y Messi,0.0,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,0.0,NaN,0.0,...,NaN,0.0,EJFC26,NaN,"<a href=""http://twitter.com/download/android"" ...",None,fr,2018-11-11 16:34:07.254,2018-11-11 16:34:07,"{'id': 207220995, 'id_str': '207220995', 'name..."
2,1.061658e+18,1.061658e+18,RT @Troyanoyoya: Con el partido que esta hacie...,0.0,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,0.0,{'created_at': 'Sun Nov 11 16:27:54 +0000 2018...,0.0,...,NaN,0.0,None,NaN,"<a href=""http://twitter.com/download/iphone"" r...",None,es,2018-11-11 16:34:07.548,2018-11-11 16:34:07,"{'id': 289264713, 'id_str': '289264713', 'name..."
3,1.061658e+18,1.061658e+18,RT @MqGuardiaCivil: Así reciben a nuestra @gua...,0.0,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,0.0,{'created_at': 'Sun Nov 11 10:25:52 +0000 2018...,0.0,...,{'created_at': 'Sat Nov 10 13:18:46 +0000 2018...,0.0,None,NaN,"<a href=""http://twitter.com/download/android"" ...",None,es,2018-11-11 16:34:07.657,2018-11-11 16:34:07,"{'id': 1011639837995266049, 'id_str': '1011639..."
4,1.061658e+18,1.061658e+18,Rakitic mierdaaaaa,0.0,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,0.0,NaN,0.0,...,NaN,0.0,None,NaN,"<a href=""http://twitter.com/download/android"" ...",None,es,2018-11-11 16:34:07.673,2018-11-11 16:34:07,"{'id': 185025378, 'id_str': '185025378', 'name..."

In [12]:
# generar fichero csv con los tweets, por si se quisiera tener en este formato y sólo con los atributos que queremos
df_final.to_csv('./data/df_final.csv')

# generar fichero excel
df_final.to_excel("./data/df_final.xlsx")

Creemos que de los datos que arroja Twitter, estos atributos serían los que tienen mayor valor para poder hacer distintos análisis y trabajo con ellos, como podría ser el análisis de sentimiento, análisis de la popularidad o influencia, análisis de relaciones entre usuarios, etc.

Para este trabajo, donde lo que vamos a analizar es el sentimiento de cada tweet en streaming, realmente solo necesitamos el texto de cada tweet, por lo que cuando se carguen los datos en el sistema nos quedaremos con el atributo "text" que será en principio el único que realmente usemos. Posteriormente veremos también si nos quedamos con algún otro atributo que pueda sernos útil para análisis o visualización.

En cuanto a las tablas que hará falta crear en la BBDD de MongoDB, vamos a generar y usar:
- Tabla general: para almacenar los tweets desde Apache Nifi, tanto en inglés como en español, y tener así una tabla master que podría usarse posteriormente como histórico si fuera necesario.
- Tabla con datos en inglés: para almacenar sólo los tweets que llegan al sistema catalogados como idioma inglés. Se podrán usar después para probar los modelos entrenados, y predecir su sentimiento.
- Tabla con datos en español: para almacenar sólo los tweets que llegan al sistema catalogados como idioma español. Se podrán usar después para probar los modelos entrenados, y predecir su sentimiento.
- Tabla para otros idiomas: una tabla donde se almacene desde Apache Nifi todos los registros que lleguen al sistema con otro idioma que no sea ni inglés ni español, por si en un futuro se quisiera usar con otros idiomas.
- Tablas streaming: se crearán tablas para almacenar en streaming los datos de inglés y español, una vez ya se hayan procesado esos datos y calculado su sentimiento. Posteriormente podrían atacarse estas tablas para explotación y visualización.